language: go

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libncurses5-dev
      - libncursesw5-dev
      - libreadline-dev
      - libgit2-dev
      - libgpm-dev

script:
  - make test && make clean &&
    if [ "$TRAVIS_OS_NAME" = 'linux' ]; then make static; fi

after_success:
  - if [ "$TRAVIS_OS_NAME" = 'linux' ] && [ "$TRAVIS_BRANCH" = 'master' ]; then make update-latest-github-release; fi
